# Configuration for the official subject tester.
server {
    listen 127.0.0.1:18083;
    server_name subject-tester.local;
    root ./YoupiBanane;
    index youpi.bad_extension;
    allowed_methods GET;
    autoindex off;
    client_max_body_size 100000001;

    location / {
        root ./YoupiBanane;
        index youpi.bad_extension;
        allowed_methods GET;
    }

    location /directory {
        root ./YoupiBanane;
        index youpi.bad_extension;
        allowed_methods GET POST;
        cgi .bla /home/mabuyahya/coding/webserv/cgi_tester;
    }

    location /post_body {
        root ./YoupiBanane;
        index youpi.bad_extension;
        allowed_methods POST;
        client_max_body_size 100;
        upload_dir ./servers/evaluation/uploads;
    }
}
