server {
    listen 127.0.0.1:8082;
    root ./servers/server1;
    allowed_methods GET POST;

    location / {
        index index.html;
        upload_dir ./servers/server1/uploads;
    }

    location /auto {
        root ./servers/server1;
        index index.html;
        upload_dir ./servers/server1/uploads;
    }
}

/login.php

password=1234
email=test@gmail.com