http {
    # root ./servers;
    # index x;
    # client_max_body_size 1G;
    #autoindex on;
    server {
        listen 127.0.0.1:8080;
        root ./servers/server1;
        allowed_methods GET POST DELETE;

        location / { 
            index index.html;
            error_page 404 /errors/404.html;
            
        }

        location /images {
            index index.html test.py;
			allowed_methods GET;
            outoindex on;
		}
        location /images/photos {
            index index.html test.py;
			allowed_methods GET;
            outoindex on;
            cgi .py usr/bin/python3;
		}
    }
    server {
    }
}

# get /
(file) = > [objects()]
/images/photos/ttt