server {
    listen 127.0.0.1:8082;
    root ./servers/server1;
    allowed_methods GET POST;

    location / {
        index index.html;
    }

    location /auto {
        root ./servers/server1;
        index index.html;
    }
}
