server {
        listen 127.0.0.1:8080;
        server_name test.com;
        root ./servers/server1;
        allowed_methods GET POST DELETE;

        location / { 
            root ./servers/server1/html;
            index index.html;
            error_page 404 /errors/404.html;
        }
        location /images {
            index index.html test.py;
			allowed_methods GET;
            autoindex on;
		}
        location /images/photos {
            index index.html test.py;
			allowed_methods GET;
            autoindex on;
            cgi .py usr/bin/python3;
		}
}