#!/usr/bin/env python3
"""Configuration parser regression tests."""

import pathlib
import socket
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "tests" / "configs"
INVALID = [
    "invalid-port.conf",
    "invalid-size.conf",
    "missing-semicolon.conf",
    "unclosed-block.conf",
    "wrong-scope.conf",
    "invalid-method.conf",
    "unknown-top-level.conf",
]


def main():
    failures = 0
    for name in INVALID:
        result = subprocess.run(
            [str(ROOT / "webserv"), str(CONFIGS / name)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=2,
        )
        if result.returncode == 0:
            failures += 1
            print(f"\033[31mFAIL\033[0m accepted {name}")
        else:
            print(f"\033[32mPASS\033[0m rejected {name}: {result.stderr.strip()}")

    process = subprocess.Popen(
        [str(ROOT / "webserv"), str(CONFIGS / "valid-minimal.conf")],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    time.sleep(0.2)
    valid = process.poll() is None
    default_error = False
    if valid:
        sock = socket.create_connection(("127.0.0.1", 8099), 2)
        sock.sendall(b"GET /missing HTTP/1.0\r\nConnection: close\r\n\r\n")
        response = b""
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            response += chunk
        sock.close()
        default_error = response.startswith(b"HTTP/1.0 404") and b"Generated by webserv" in response
    process.terminate()
    process.wait(timeout=2)
    if valid:
        print("\033[32mPASS\033[0m accepted valid-minimal.conf")
    else:
        failures += 1
        print("\033[31mFAIL\033[0m rejected valid-minimal.conf")
    if default_error:
        print("\033[32mPASS\033[0m generated default error page")
    else:
        failures += 1
        print("\033[31mFAIL\033[0m default error page")

    print(f"\n{9 - failures} passed, {failures} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
